### ISSUE TITLE
Dropdown Text as Parameter

### ISSUE THREAD

**Issue by dirko0816** [pippogsm/droptabs#5]
Hi

I love your plugin.
Here's a small improvement:

The default text of the dropdown-tab is hardcoded as "Dropdown"
on line 58 `$('>a', dropdown).html('Dropdown <b class="caret"></b>');` 

For multilanguage purposes it would be a nice feature to make this configurable
ie: add after Line 16 this: `dropdownLabel              : "Dropdown",`
and change the above code to `$('>a', dropdown).html(s.dropdownLabel + ' <b class="caret"></b>');`

then this can be set by parameters: `$('.droptabs').droptabs({dropdownLabel: 'myLabel'});`

hope this helps
Dirko

**Comment by eckerson** [comment]
I was working on a PR to take care of this issue, and I'm wondering if it would be better to pull that from the DOM when it initializes (since you have to manually add the dropdown tab to the DOM anyway).  That way when you create the tabs, you can't have your initial dropdown label be "Foo" and the options set it to "Bar" (since the option would only be referenced when a tab is shown, not on-init).

I'll try to have a PR for this in a bit.
